const patientDataLabels = {
  first_name: 'نام',
  last_name: 'نام خانوادگی',
  fathers_name: 'نام پدر',
  mothers_name: 'نام مادر',
  gender: 'جنسیت',
  national_id: ' کد ملی',
  birthday: ' تاریخ تولد',
  birthday_province: 'استان محل تولد',
  birthday_city: 'شهر محل تولد',
  living_province: 'استان محل زندگی',
  living_city: 'شهر محل زندگی',
  delivery_type: 'نوع زایمان',
  delivery_age: ' سن زایمان',
  birthday_weight: ' وزن هنگام تولد',
  number_of_children: ' تعداد فرزندان',
  parent_family: 'نسبت فامیلی والدین',
  hospital_history: 'سابقه بستری در بیمارستان',
  systemic_disease_history: 'سابقه بیماری سیستمیک',
  cataracte_history: 'سابقه کاتاراکت در خانواده',
  other_eye_disease: 'سابقه سایر بیماری های چشمی',
  age_at_diagnosis_year: ' سن هنگام تشخیص بیماری (سال)',
  age_at_diagnosis_month: ' سن هنگام تشخیص بیماری (ماه)',
  diagnosed_by: 'تشخیص بیماری توسط',
  phone: ' شماره تماس',
};

export default patientDataLabels;
